### PR TITLE
Fixed behavior on ensure = absent

### PR DESCRIPTION
**Pull request by codec**
I removed the selector in useraccount.pp as all resources already handle $ensure properly.

Also, the ssh_authorized_key resource in lookupkey.pp doesn't need the target property as it defaults to ~user/.ssh/authorized_keys. Puppet somehow got stuck on this trying to resolve the uid of the already removed user.

### CODE REVIEW

**Comment by dcsobral** [comment]
Target is there to get around a bug on old Puppet versions. See https://github.com/dcsobral/puppet-users/commit/c6adce6402cd2e815aa623fcd3e3c16ebce09a90.

The selector is there to avoid expensive call to findDirs.sh in the absence case.

**Comment by codec** [comment]
But are you aware that $ensure=absent will never work properly with that selector?

**Comment by dcsobral** [comment]
It does work properly for me. What issues do you have?

**Comment by codec** [comment]
With a manifest like this

```
users::massuseraccount { 'admin':
  ensure => absent,
  groups => [ 'foo', 'bar' ]
}

users::masskeys { 'admin';
  ensure => absent
}
```

the module would remove users, but home directories and `authorized_keys` stay, because the selector only handles the `present` case. This also makes all `$ensure` selectors inside the resources useless, as it's always `present`.

The problem with `ssh_authorized_key` and the `target` property is that it triggers puppet to resolve the UID on the authorized_keys file resulting in an error message

```
err: /Stage[main]/Admin/Users::Masskeys[admin]/Users::Lookupkey[user]/Ssh_authorized_key[user_user@host]: Could not evaluate: can't find user for 1000
```

because the user is already absent on the system. Which bug does this work around? Can't see a bug# in the commit you referred to.

**Comment by dcsobral** [comment]
Actually, non-removal of home directory is by design. Ok, undocumented design, but the idea is not losing data that might be stored in the home directory of someone who has been removed. I admit it might be inconvenient if that is not a concern, but disk space is.

I think the bug is this one; http://projects.puppetlabs.com/issues/2124. It fits that my Lenny puppet clients did not have the issue, but the Ubuntu ones did.

**Pull request closed without merging**
